const express = require("express");
const { requireLogin } = require("./../../utils.js");
const gameController = require("./controller");
const router = express.Router();
router.get("/review", requireLogin, gameController.review);
router.get("/game", requireLogin, gameController.startGame);
router.get("/gameInfo", requireLogin, gameController.getGameInfo);
router.get("/gameMoves", requireLogin, gameController.getGameMoves);
router.post("/rematch", requireLogin, gameController.rematch);
module.exports = router;